### PR TITLE
merged vhost configs, resolved alias/root bug, moved backuppc to doma…

### PR DESCRIPTION
**Pull request by lukas2511**
…in root, removed settings that shouldn't be defined as part of a vhost, added section headers in config to make things clear

### CODE REVIEW

**Comment by Zloy** [comment]
Sorry for late answer, I was on a vacation. I cannot merge that, because you've completely removed insecure config. You'd blamed previously the particular line. Why not just fix it?

**Comment by lukas2511** [comment]
If you look at the changes you'll see that i merged the two vhosts into one, because it's not necessary to keep two

**Comment by Zloy** [comment]
Merging these two configs makes things hard to read and maintain. If you like to fix the bug, please do just that.

**Comment by lukas2511** [comment]
I personally think it makes things easier to maintain as you don't have to maintain two configs, but if you don't like it then just close this and we'll just forget about it

**Comment by Zloy** [comment]
Thank you for drawing my attention to root/alias lines. I'll try to fix that on my own. Thank you and good luck!

**Pull request closed without merging**
